# .github/workflows/space-shooter.yml
name: Space Shooter

on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정 실행
  workflow_dispatch: # 수동 실행 가능

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: czl9707/gh-space-shooter@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          user: devscarycat
          output: space-shooter.gif
          background: '000000' # 배경색 (검정)
